cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.time}
    --gres=gpu:{resources.gpu}
default-resources:
  - partition=cpuq
  - mem_mb=1000
  - time="00:10:00"
  - gpu=0
max-jobs-per-second: 100
max-status-checks-per-second: 20
local-cores: 1
latency-wait: 90
jobs: 800
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True
verbose: True
reason: True
