import pandas as pd
from glob import glob

configfile: 'config/config.yaml'

df=(pd.read_table(config['samples'], dtype={'sample_id': str, 'cram':str})
	.set_index('sample_id', drop=False)
	.sort_index()
)

include: 'rules/impg.smk'
include: 'rules/bedtools.smk'
include: 'rules/samtools.smk'
include: 'rules/faidx.smk'
include: 'rules/pggb.smk'
include: 'rules/odgi.smk'
include: 'rules/bwa-mem2.smk'
include: 'rules/gfainject.smk'
include: 'rules/gafpack.smk'
include: 'rules/cosigt.smk'
include: 'rules/megadepth.smk'

rule cosigt:
	input:
		expand(config['output'] + '/cosigt/{sample}/{region}/cosigt_genotype.tsv', sample=df['sample_id'].tolist(), region=config['region'])

rule annotate:
	input:
		expand(config['output'] + '/odgi/untangle/{region}.gggenes.tsv', region=config['region'])

rule debug:
	input:
		expand(config['output'] + '/megadepth/{sample}/{region}.all.bw', sample=df['sample_id'].tolist(), region=config['region'])