import pandas as pd

configfile: 'config/config.yaml'

df=(pd.read_table(config['samples'], dtype={'sample_id': str, 'cram':str})
	.set_index('sample_id', drop=False)
	.sort_index()
)

include: 'rules/extract.smk'
include: 'rules/pggb.smk'
include: 'rules/odgi.smk'
include: 'rules/bwa-mem2.smk'
include: 'rules/gfainject.smk'
include: 'rules/gafpack.smk'
include: 'rules/cosigt.smk'

rule cosigt:
	input:
		expand(config['output'] + '/cosigt/{sample}/{region}/cosigt_genotype.tsv', sample=df['sample_id'].tolist(), region=config['region'])
